### ISSUE TITLE
how realtime live tick data in metetrader 4?

### ISSUE THREAD

**Issue by rahmangunawans** [ejtraderLabs/ejtraderIQ#1]
how make multi pair realtime live tick?

with https://github.com/FX31337/FX-Data-Convert-Action/blob/master/src/fx-data-convert-from-csv.py

**Comment by traderpedroso** [comment]
We do not support metatrader 4 only metatrader 5  [ejtraderMT](https://github.com/ejtraderLabs/ejtraderMT) and its supported multiples symbol real-time 

and for IQoption it's not possible, but a workaround could be done 


```python

# pip install ejtraderTH // its for easy threading
# pip install ejtraderIQ
from ejtraderIQ import IQOption
import ejtraderTH as th
import pandas as pd

api = IQOption('tribolinux@gmail.com','tribopass@123','DEMO')



Symbols = ['EURUSD', 'GBPUSD']




def get_data(symbols):
    
    data = api.history(symbols,"M1",5)
    data.columns = [f'{symbols}_open', f'{symbols}_high',
                                                f'{symbols}_low', f'{symbols}_close', f'{symbols}_volume']
    
    
    return data

processed_data = th.start(get_data, Symbols)

for data in processed_data:
    print(data)

# its time elapsed
th.elapsed(output=True)

```

**Comment by rahmangunawans** [comment]
> We do not support metatrader 4 only metatrader 5 [ejtraderMT](https://github.com/ejtraderLabs/ejtraderMT) and its supported multiples symbol real-time
> 
> and for IQoption it's not possible, but a workaround could be done

iq option combined with convert_iq_to_mt.py or convert_csv_to_mt.py?
