### ISSUE TITLE
Bot always see Profit as a loss

### ISSUE THREAD

**Issue by driesgouwss** [ejtraderLabs/ejtraderIQ#3]
Bot does not give correct profit outcome???

**Comment by traderpedroso** [comment]
> Bot does not give correct profit outcome???



> Bot does not give correct profit outcome???

I believe you may not be using the correct win check, as there are two options depending on whether you are operating in a digital or binary mode. If this is not the case, could you please explain more clearly? Sharing a part of the code that is checking for win or loss could be useful. Could you clarify exactly which part of the code is being used to calculate profit?

```python
api.checkwin(id)

# example check win Digital 
id = api.buy(volume,symbol,timeframe)
win = api.checkwin(id)

if win > 0:
    print(("WIN"+'\n'))
elif win < 0:                                            
    print(("LOSS"+'\n'))
else:
    print(('Tied '+'\n'))
    
    
# example check win Turbo
id = api.buy(volume,symbol,timeframe,turbo=True)
win = api.checkwin(id,turbo=True)

if win > 0:
    print(("WIN"+'\n'))
elif win < 0:                                            
    print(("LOSS"+'\n'))
else:
    print(('Tied '+'\n'))    
```

**Comment by driesgouwss** [comment]
We trade Binary and the results seems to be correct but the code sees every trade as a loss. See code bellow:

                                if status:
                                        while True:
                                                try:
                                                        status,valor = API.check_win_digital_v2(id) if operacao == 1 else API.check_win_v3(id)
                                                except:
                                                        status = True
                                                        valor = 0

                                                if status:
                                                        valor = valor if valor > 1 else float('-' + str(abs(valor_entrada)))
                                                        lucro += round(valor, 2)

                                                        print('Resultado operação: ', end='')

                                                        print('WIN /' if valor > 0 else 'LOSS /' , round(valor, 2) ,'/', round(lucro, 2),('/ '+str(i)+ ' GALE' if i > 0 else '' ))

**Comment by driesgouwss** [comment]
I have got it working thanks for the help,

I have a new problem after a loss the bot does not check indicators I have added some additional code but without success please see bellow:

[mhi1.zip](https://github.com/ejtraderLabs/ejtraderIQ/files/11479865/mhi1.zip)

**Comment by traderpedroso** [comment]
> I have got it working thanks for the help,
> 
> I have a new problem after a loss the bot does not check indicators I have added some additional code but without success please see bellow:
> 
> [mhi1.zip](https://github.com/ejtraderLabs/ejtraderIQ/files/11479865/mhi1.zip)

MHI Martingale Bot

Hello, we have refactored the code and correctly integrated the ejtraderIQ API. Now, the bot is working as expected. You just need to add your configurations such as login, password, and choose the type of MHI you want.

You can find the bot under the examples directory in our repository [here](https://github.com/ejtraderLabs/ejtraderIQ/blob/main/examples/mhi-martingaleBot.py).

Please follow the link and adjust the settings according to your preferences before running the bot.
