### ISSUE TITLE
active_suspended: rejected by risks

### ISSUE THREAD

**Issue by Rohanlogs** [ejtraderLabs/ejtraderIQ#4]
Hello, what does this error mean?
Happens on api.sell & api.buy() 

Login gets through OK, also balance and other functions are working, but sell/buy throws this error.
I am trying to place an order on DEMO account. Tried on a few accounts, same thing happens.

```
Error put 
False {'message': 'active_suspended: rejected by risks'}
```

**Comment by traderpedroso** [comment]
> Hello, what does this error mean? Happens on api.sell & api.buy()
> 
> Login gets through OK, also balance and other functions are working, but sell/buy throws this error. I am trying to place an order on DEMO account. Tried on a few accounts, same thing happens.
> 
> ```
> Error put 
> False {'message': 'active_suspended: rejected by risks'}
> ```
Asset with high volatility deactivated due to high risk exposure.
